### ISSUE TITLE
Pull request template tidak ada

### ISSUE THREAD

**Issue by slowy07** [bellshade/Java#104]
setelah major update dengan menggunakan maven, hasil dari pull request sebelumnya terdapat beberapa file yang hilang antara lain yaitu pull request template, oleh karena itu, buat kembali pull request template dan issue template

folder terdapat pada

```
.github/pull_request_template.md
```
sedangkan pada issue template terdapat pada
```
.github/ISSUE_TEMPLATE/feature_report.md
```

sisa:
- [x] `funding.yml`
- [x] `CODEWONER`
- [x] `pull_request_template.md`
- [x] `issues_template`

**Comment by random-prog** [comment]
sisa:
- [] `funding.yml`
- [] `CODEWONER`
- [] `pull_request_template`
