### ISSUE TITLE
java intermediate

### ISSUE THREAD

**Issue by slowy07** [bellshade/Java#11]
# java intermediate
yang belum terepehui pada repo java
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56

**Comment by random-prog** [comment]
SELESAI. LIST-LIST SUDAH DIPENUHI
