### ISSUE TITLE
fix: error package name

### ISSUE THREAD

**Issue by malvinval** [bellshade/Java#118]
**Masalah**
Terdapat error karna deklarasi nama package yang tidak sesuai pada file [GCD.java](https://github.com/bellshade/Java/blob/main/src/main/java/maths/GCD.java)

**Solusi**
Mengganti deklarasi nama package `math` menjadi `maths`

**Desktop (please complete the following information):**
 - OS: ``Linux`` 
 - Java: ``javac``  

terima kasih !

**Comment by slowy07** [comment]
close karena pull request sudah di merge
