### ISSUE TITLE
java konstruktor

### ISSUE THREAD

**Issue by slowy07** [bellshade/Java#16]

**Comment by slowy07** [comment]
yes, save file on folder ( create folder named ``JavaKonstrutktor``) ``intermediate/JavaKonstruktor```, writting with some information about java construtor on markdown file and create one source code, with indonesia language :100:

**Comment by fairusatoir** [comment]
sudah dikerjakan di #35

**Comment by slowy07** [comment]
close sudah dikerjakan pada PR nomor #35
