### ISSUE TITLE
Java Conversion

### ISSUE THREAD

**Issue by random-prog** [bellshade/Java#21]
Convertion yang ada sekarang hanya DecimalToOctal

update ref @slowy07 
- [x] #31
- [x] #32
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44

**Comment by sautmanurung1** [comment]
saya sudah ada mas DecimalToHex dan DecimalToBiner

**Comment by fairusatoir** [comment]
mas @slowy07 , #41 , #42 , #43 bisa assign ke saya ?

**Comment by random-prog** [comment]
semua dah di ceklist ya, jadi kami closed. Terima Kasih telah berkontribusi🤙
